In [4]:
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np
import scipy as sp
import pandas as pd
from sklearn import preprocessing

In [3]:
data = pd.read_csv("./movies_classification.csv")
data.head(10)

      budget original_language  popularity     revenue  vote_average
0  237000000                en  150.437577  2787965087           7.2
1  300000000                en  139.082615   961000000           6.9
2  245000000                en  107.376788   880674609           6.3
3  250000000                en  112.312950  1084939099           7.6
4  260000000                en   43.926995   284139100           6.1
5  258000000                en  115.699814   890871626           5.9
6  260000000                en   48.681969   591794936           7.4
7  280000000                en  134.279229  1405403694           7.3
8  250000000                en   98.885637   933959197           7.4
9  250000000                en  155.790452   873260194           5.7

In [15]:
data["original_language"].unique().size

37

In [6]:
num_data = pd.get_dummies(data)
num_data.head(10)

,budget,popularity,revenue,vote_average,original_language_af,original_language_ar,original_language_cn,original_language_cs,original_language_da,original_language_de,...,original_language_ru,original_language_sl,original_language_sv,original_language_ta,original_language_te,original_language_th,original_language_tr,original_language_vi,original_language_xx,original_language_zh
0,237000000,150.437577,2787965087,7.2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,300000000,139.082615,961000000,6.9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,245000000,107.376788,880674609,6.3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,250000000,112.312950,1084939099,7.6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,260000000,43.926995,284139100,6.1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,258000000,115.699814,890871626,5.9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,260000000,48.681969,591794936,7.4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,280000000,134.279229,1405403694,7.3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,250000000,98.885637,933959197,7.4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,250000000,155.790452,873260194,5.7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
mm_scaler = preprocessing.MinMaxScaler()
mm_scaler.fit(num_data)
norm_data = pd.DataFrame(columns=num_data.columns, data=mm_scaler.transform(num_data))
norm_data.head()

,budget,popularity,revenue,vote_average,original_language_af,original_language_ar,original_language_cn,original_language_cs,original_language_da,original_language_de,...,original_language_ru,original_language_sl,original_language_sv,original_language_ta,original_language_te,original_language_th,original_language_tr,original_language_vi,original_language_xx,original_language_zh
0,0.623684,0.171815,1.000000,0.72,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.789474,0.158846,0.344696,0.69,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.644737,0.122635,0.315884,0.63,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.657895,0.128272,0.389151,0.76,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.684211,0.050169,0.101916,0.61,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0